# Generated by Django 5.2.4 on 2025-10-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_offer_description_order_orderitem_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
    ]
