# Generated by Django 5.2.4 on 2025-10-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_profile_email_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('name', 'offer_type')},
        ),
    ]
