# Generated by Django 5.2.4 on 2025-10-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_offer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_ticket_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.offer'),
        ),
    ]
