# Generated by Django 5.2.4 on 2025-10-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_orderitem_final_ticket_key_orderitem_purchase_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='final_ticket_key',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='purchase_key',
        ),
    ]
